name: Prevent github from suspending scheduled actions
on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:
permissions:
  contents: write
  actions: write
  id-token: write
  pages: write
  checks: write
  pull-requests: write
  deployments: write
  repository-projects: write
  statuses: write
jobs:
  keepalive:
    name: Create dummy commit to prevent github from suspending actions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2 # using the workflow with default settings
