name: Prevent github from suspending scheduled actions
on:
  schedule:
    - cron: "0 0 * * 3"
  workflow_dispatch:
permissions:
  contents: write

jobs:
  keepalive:
    name: Create dummy commit to prevent github from suspending actions 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1 # using the workflow with default settings
